### ISSUE TITLE
Failing test: cb when stream is ended

### ISSUE THREAD

**Issue by christianbundy** [ssbc/muxrpc#41]
This is in the `v6` branch, which looks like it's the default branch for this repo (?):

```
# cb when stream is ended
not ok 20 should be equal
  ---
    operator: equal
    expected: null
    actual:   {}
    at: close (/home/christianbundy/src/ssbc/muxrpc/stream.js:94:48)
  ...
```

**Comment by dominictarr** [comment]
I was looking at this today. I think that the test is actually incorrect.
the first test, the stream ends without sending anything at all. but packet-stream-codec expects a "goodbye" packet, and it's an error if it doesn't get that. in pull-reader@1.3 it's an error if you expect to read bytes and don't get them, but it wasn't before, which was letting this pass, but now that pull-reader has better behaviour, it fails. I'm just gonna fix the test so it passes.

**Comment by christianbundy** [comment]
Thanks!

**Comment by dominictarr** [comment]
@christianbundy oh yeah: v6 is the default branch. one time, I rewrote this, made the code waaay better, and added back pressure, but I didn't get the adjustment of backpressure right, and it although all local tests passed other people's apps sudden went really slow to download blobs, etc... so I reverted to v6. and v7 has been on the backburner since then
